const RESULTS_SEARCH_LIMIT = 20;
const DEFAULT_SORT_FIELD = 'price';
const DEFAULT_FIRST_PAGE_OF_RESULT = 1;

export {
  DEFAULT_FIRST_PAGE_OF_RESULT,
  RESULTS_SEARCH_LIMIT,
  DEFAULT_SORT_FIELD,
};
